version: "3"

services:
  db:
    image: mysql:8.0
    volumes:
      - ./db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "wordpress"
      MYSQL_USER: "wordpress"
      MYSQL_PASSWORD: "password"

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress-data:/var/www/html
      - ./wp-content:/var/www/html/wp-content
      - ./wordpress/apache/apache.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./wp-config.php:/var/www/html/wp-config.php

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./index.html:/var/www/html/index.html:ro
    depends_on:
      - wordpress

volumes:
  wordpress-data:
